### ISSUE TITLE
Seems like the script is not executing

### ISSUE THREAD

**Issue by kuncevic** [AlexanderLindkjaer/alfred-bash-execute-workflow#1]
I just have the following script(remove-my-file.sh)  that just removing the file from the system:

```
#!/bin/sh

/bin/rm -rf path-to-my-file
```

So after I run the script with Alfred 
- I've got iTerm popping up 
- Then getting Alfred notification that script was run 

But in reality seems really it is not, because the file is still there.

Any ideas?

p.s
Also tried to use bash insteard of iterm but still same outcome 
![image](https://user-images.githubusercontent.com/1283734/107827004-050d7c00-6dda-11eb-939d-3a2f76366eac.png)

If I run the script manually in terminal in works, so there is no issues in a script.
Also I set it `chmod +x script-name.sh` but seems it didn't help either

**Comment by AlexanderLindkjaer** [comment]
Hey @kuncevic 
I have not used this for a while (Many Mac and Alfred updates ago), so won't be able to debug it. If I had to guess, I think you on the to something with the permissions. Maybe try a simple echo 'hello world' script and see if that runs. That way you will know if it's the execution of all scripts or just the one script containing something that requires it.

**Comment by kuncevic** [comment]
Fixed with

```
script_path=$1
script_dir=$(dirname "${script_path}")
cd "${script_dir}"
"${script_path}"
```
